spring:
  datasource:
         url: jdbc:mysql://localhost:3306/shiro
         userName: root
         password: root
  thymeleaf:
         cache: true
         check-template-location: true
         content-type: text/html
         enabled: true
         encoding: utf-8
         mode: HTML5
         prefix: classpath:/templates/
         suffix: .html
  cache:
        ehcache:
          config:  classpath:/ehcache.xml
debug:
   true
mybatis:
  mapper-locations:  classpath:/mapping/*Mapper.xml
# 打印sql
logging:
  level:
     com.example.demo.dao : debug

