spring:
  datasource:
         url: jdbc:mysql://localhost:3306/shiro
         username: root
         password: root
#  mvc:
#    view:
#       prefix:  /WEB-INF/jsp/
#       suffix:  .jsp

debug:
   true
mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
